confcenter/urls.py
from django.http import  HttpResponse
from django.conf.urls import patterns, include, url
from upload.views import upload_file, anal_acc, list_values, upload_progress, headpiece, dummy, projects, plans

from upload.models import Oses

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
from confcenter import settings
from django.http import  HttpResponse
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'confcenter.views.home', name='home'),
    # url(r'^confcenter/', include('confcenter.foo.urls')),

    ('^$', headpiece),
    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^upload/$', upload_file),
    url(r'^upload/$', upload_file),
    url(r'^projects/$', projects),
    url(r'^plans/$', plans),
    url(r'^about/$', dummy),
    url(r'^upload/progress/$', upload_progress, name='upload_progress'),
    url(r'^upload/anal_acc/$', anal_acc),
    url(r'^values/$', list_values),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^robots.txt', lambda r: HttpResponse("User-agent: *\nDisallow: /upload", mimetype="text/plain")),

)

if settings.DEBUG:
    urlpatterns += patterns('', url(r'^media/(?P<path>.*)$', 'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}),
    )

upload/forms.py
__author__ = 'vss'
# -*- coding: utf-8 -*-
from django import forms
from upload.models import OsTypes, Oses
from django.utils.translation import ugettext as _



class ConfUploadForm(forms.Form):

    OS_TYPES = []
    AllOsTypes = OsTypes.objects.all()

    OS_TYPES.append((_(u'Auto-detect'), [(0, _('Auto-detect'))]))

    for type in AllOsTypes:
        AllOsVers = Oses.objects.filter(ostypes=type)
        OSES_LIST = []
        for ver in AllOsVers:
            OSES_LIST.append((ver.id, type.os_vendor + ' ' + type.os_name + ' ' + ver.os_level))
        OS_TYPES.append((type.os_vendor + ' ' + type.os_name, (OSES_LIST)))

    ostype = forms.ChoiceField(choices=OS_TYPES, label=_(u'choose_ostype_upload'))
    file  = forms.FileField(label=_(u'choose_file_upload'))

confcenter/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">
{% load i18n %}
<html>
<head>
    <meta charset="utf-8" />
    {% load static %}
    {% get_static_prefix as STATIC_PREFIX %}
    <link rel='stylesheet' href='/media/upload/css/style.css'>
    <script src="http://code.jquery.com/jquery-1.8.3.js"></script>
    <script src="http://code.jquery.com/ui/1.9.2/jquery-ui.js"></script>
    <link rel="stylesheet" href="http://code.jquery.com/ui/1.9.2/themes/base/jquery-ui.css" />
    {% block js %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
    <style type="text/css">{% block style %}{% endblock %}</style>
    <script type="text/javascript">
        function hideShow(el){
            $(el).toggleClass('show').next('div.hideCont').slideToggle('normal');
            return false;

        };
    </script>

    <script type="text/javascript">
        var IsVisible=0;
        function hideShowAll(el){
            if  (!IsVisible)
            {$(el).show('slow');
             $('.plusBtn').hide();
             $('.minusBtn').show();
             IsVisible=1;}
            else {$(el).hide('slow');
                $('.plusBtn').show();
                $('.minusBtn').hide();
                IsVisible=0;}

              return false;
        };
    </script>

    <script type="text/javascript">
        $(document).ready(function(){
            var browser = navigator.appName;
            if (browser =="Microsoft Internet Explorer") {
                $('.news').css ('color',"#ACACAC");

            }
            else {$('.news').css ('color',"white");}
            $('.newsDD').show('clip', 2000);
        });

    </script>

    <nav id="globalheader">

        <ul id="globalnav" role="navigation">
            <li ><a href="/"><span>{% trans "Main" %}</span></a></li>
            <li class="nav_upload"><a href="/upload/"><span>{% trans "configuration_analysis" %}</span></a></li>
            <li class="nav_projects"><a href="/projects/"><span>{% trans "projects" %}</span></a></li>
            <li class="nav_plans"><a href="/plans"><span>{% trans "plans" %}</span></a></li>

        </ul>
    </nav>
</head>
<body>

<!--<h1>Confcenter</h1>-->

{% block content %}{% endblock %}
{% block footer %}
    <div id="footer">
        <hr color="#F9F9F9"/>
        <p class="piped">
           Powered by Django. NixConf.com

        </p>
    </div>
{% endblock %}

</body>
</html>

confcenter/templates/confupload_form.html
{% extends "base.html" %}
{% load i18n %}

{% block title %} {% trans "conf_upload_form_title" %} {% endblock %}

{% block js %}
    <script src="{{ MEDIA_URL  }}/js/nginx_upload.js" type="text/javascript" xmlns="http://www.w3.org/1999/html"></script>
{% endblock %}
{%  block style %}
    #globalheader #globalnav li.nav_upload a {
    background: #98B85B;
    color: #cae285;
    text-shadow: 1px 1px #6E883F;
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#98B85B', endColorstr='#98B85B',GradientType=0 );
    }

{% endblock %}
{% block content %}
    <div id="content_conf">
        {% if form.errors %}
            <p style="color: red;">
                Please correct the error{{ form.errors|pluralize }} below.
                {{ form.errors }}
            </p>
        {% endif %}

        <form id="upload_form" enctype="multipart/form-data" method="post">
            <table id="upload_table">
                <tr><th><label for="id_ostype">{% trans "choose_ostype_upload" %}</label></th><td><select name="ostype" id="id_ostype">
                    <optgroup label={% trans "Auto-detect" %}>
                        <option value="0">{% trans "Auto-detect" %}</option>
                    </optgroup>
                </select></td></tr>
                <tr><th><label for="id_file">{% trans "choose_file_upload" %}</label></th><td><input type="file" name="file" id="id_file" /></td></tr>
                <tr><th></th><td><input type="submit" id="id_submit"  value={% trans "button_submit_upload" %} /></td></tr>
            </table>


        </form>
        <div id="progressbar" style="display: NONE">
            <p style="background: none; position: absolute; left: 450px; font-size: 8pt"> {% trans "Loading" %} </p>
        </div>

        <div id="analyze" style="display: NONE" align="center">
            <p>{% trans "analyze_upload" %}</p>
            <img id="analyze_progress" src="/media/upload/img/progressbar.indicator.gif" />
        </div>

    </div>

{% endblock %}

confcenter/templates/dummy.html
{% extends "base.html" %}
{% load i18n %}

{% block title %} This page is under construction {% endblock %}

{% block js %}
    <script src="{{ MEDIA_URL }}/js/test.js" type="text/javascript" xmlns="http://www.w3.org/1999/html"></script>
{% endblock %}

{% block content %}
    <div id="content_conf">
    <p> This page is under construction</p>
    </div>
{% endblock %}

confcenter/templates/headpiece.html
{% extends "base.html" %}
{% load i18n %}

{% block title %} Configuration Analysis {% endblock %}

{% block content %}
<div id="headpiece">
  <DL class="news">

      {% for item in news %}
          <DD class="newsDD">
              {{ item.date }} - {{ item.text }}
          </DD>
      {% endfor %}
{#     <DD class="fst">#}
{#        18.02.2012 Добавлен раздел "Новости"#}
{#     </DD>#}
{#      <DD class="scnd">#}
{#          18.02.2012 Исправлена ошибка записи больших таблиц в pdf#}
{#      </DD>#}
{#      <DD class="thrd">#}
{#          17.02.2013 Создан сайт#}
{#      </DD>#}
  </DL>

</div>

{% endblock %}

confcenter/templates/plans.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Планы{% endblock %}

{% block js %}
    <script src="{{ MEDIA_URL }}/js/test.js" type="text/javascript" xmlns="http://www.w3.org/1999/html"></script>
{% endblock %}
{%  block style %}
    #globalheader #globalnav li.nav_plans a {
    background: #98B85B;
    color: #cae285;
    text-shadow: 1px 1px #6E883F;
    }


{% endblock %}
{% block content %}
    <div id="content_conf">
        <h1> Анализ конфигураций: </h1>
            <ol class="about">
               <li>Добавить поддержку ОС Solaris (осуществлять разбор выводов утилиты explorer).</li>
               <li>Добавить поддержку ОС RHEL (осуществлять разбор конфигурационных файлов explorer).</li>
               <li>Добавить поддержку выводов VRTSexplorer по различным платформам.</li>
               <li>Добавить базовые модули анализа полученной конфигурации оборудования.</li>
            </ol>
    </div>
{% endblock %}

confcenter/templates/plans_en.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Plans{% endblock %}

{% block js %}
    <script src="{{ MEDIA_URL }}/js/test.js" type="text/javascript" xmlns="http://www.w3.org/1999/html"></script>
{% endblock %}
{%  block style %}
    #globalheader #globalnav li.nav_plans a {
    background: #98B85B;
    color: #cae285;
    text-shadow: 1px 1px #6E883F;
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#98B85B', endColorstr='#98B85B',GradientType=0 );
    }


{% endblock %}
{% block content %}
    <div id="content_conf">
        <h1> Configuration Analysis: </h1>
        <ol class="about">
            <li>OS Solaris support (create explorer output analysis).</li>
            <li>OS RHEL support (create explorer configuration files analysis).</li>
            <li>VRTSexplorer output support in different platforms.</li>
            <li>Develop basic modules for configuration analysis.</li>
        </ol>
    </div>
{% endblock %}

confcenter/templates/plans_ru.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Планы{% endblock %}

{% block js %}
    <script src="{{ MEDIA_URL }}/js/test.js" type="text/javascript" xmlns="http://www.w3.org/1999/html"></script>
{% endblock %}
{%  block style %}
    #globalheader #globalnav li.nav_plans a {
    background: #98B85B;
    color: #cae285;
    text-shadow: 1px 1px #6E883F;
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#98B85B', endColorstr='#98B85B',GradientType=0 );
    }


{% endblock %}
{% block content %}
    <div id="content_conf">
        <h1> Анализ конфигураций: </h1>
            <ol class="about">
               <li>Добавить поддержку ОС Solaris (осуществлять разбор выводов утилиты explorer).</li>
               <li>Добавить поддержку ОС RHEL (осуществлять разбор конфигурационных файлов explorer).</li>
               <li>Добавить поддержку выводов VRTSexplorer по различным платформам.</li>
               <li>Добавить базовые модули анализа полученной конфигурации оборудования.</li>
            </ol>
    </div>
{% endblock %}

confcenter/templates/projects_en.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Projects{% endblock %}

{% block js %}
    <script src="{{ MEDIA_URL }}/js/test.js" type="text/javascript" xmlns="http://www.w3.org/1999/html"></script>
{% endblock %}
{%  block style %}
    #globalheader #globalnav li.nav_projects a {
    background: #98B85B;
    color: #cae285;
    text-shadow: 1px 1px #6E883F;
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#98B85B', endColorstr='#98B85B',GradientType=0 );
    }


{% endblock %}
{% block content %}
    <div id="content_conf">

        <h1>Configuration Analysis: </h1>
        <p class="about">   The main purpose of this project is to create automatic processing for server configuration output.
            Now, in this project processing and analysis for IBM Power snap are realized.
            As a result the page with server data (server partitions) is displayed.  You can export data in PDF as well.
        <p class="about"> Reports examples: </p>
        <ul class="about">
            <li> <a href="{{ MEDIA_URL }}/upload/datafiles/snapreport_XXXX-XXX_XXXXXXXXX_gc_en.pdf">
                Report generated for snap collected with gc keys (general information only)</a></li>
            <li><a href="{{ MEDIA_URL }}/upload/datafiles/snapreport_XXXX-XXX_XXXXXXXXX_ac_en.pdf">
                Report generated for snap collected with ac keys (all information)</a></li>
            <li><a href="{{ MEDIA_URL }}/upload/datafiles/snapreport_XXXX-XXX_XXXXXXXXX_gc.AIX.confdump">
                Report generated in site-format for snap collected with gc keys</a></li>
            <li>
                <a href="{{ MEDIA_URL }}/upload/datafiles/snapreport_XXXX-XXX_XXXXXXXXX_ac.AIX.confdump">
                    Report generated in site-format for snap collected with ac keys</a>
            </li>
        </ul>


        </p>
    </div>
{% endblock %}

confcenter/templates/projects_ru.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}Проекты{% endblock %}

{% block js %}
    <script src="{{ MEDIA_URL }}/js/test.js" type="text/javascript" xmlns="http://www.w3.org/1999/html"></script>
{% endblock %}
{%  block style %}
    #globalheader #globalnav li.nav_projects a {
    background: #98B85B;
    color: #cae285;
    text-shadow: 1px 1px #6E883F;
    filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#98B85B', endColorstr='#98B85B',GradientType=0 );
    }


{% endblock %}
{% block content %}
    <div id="content_conf">

            <h1>Анализ конфигураций: </h1>
        <p class="about">    Цель проекта - создать инструмент автоматической обработки конфигурационных выводов с оборудования.
            Сейчас в данном проекте реализована обработка и разбор выводов утилиты snap с серверов IBM Power.
            Результатом разбора является страница с данными о сервере (разделе сервера). Существует возможность выполнить экспорт конфигурации в PDF файл.
            <p class="about"> Примеры создаваемых отчетов: </p>
            <ul class="about">
                <li> <a href="{{ MEDIA_URL }}/upload/datafiles/snapreport_XXXX-XXX_XXXXXXXXX_gc_ru.pdf">
                    Отчет из вывода snap с ключами gc (general information only)</a></li>
                <li><a href="{{ MEDIA_URL }}/upload/datafiles/snapreport_XXXX-XXX_XXXXXXXXX_ac_ru.pdf">
                    Отчет из вывода snap с ключами ac (all information)</a></li>
                <li><a href="{{ MEDIA_URL }}/upload/datafiles/snapreport_XXXX-XXX_XXXXXXXXX_gc.AIX.confdump">
                    Промежуточный вывод в формате сайта для snap с ключами gc</a></li>
                <li>
                    <a href="{{ MEDIA_URL }}/upload/datafiles/snapreport_XXXX-XXX_XXXXXXXXX_ac.AIX.confdump">
                        Промежуточный вывод в формате сайта для snap с ключами ac</a>
                </li>
            </ul>
        </p>
    </div>
{% endblock %}